#!/bin/bash

if [ $# -eq 0 ]
    then
    echo "Invalid input. Please supply one or more files."

else
    for file in $@
        do

        if [ -e $file ]; then
            if [ -d $file ]; then
                mv "$file" "._$file"
            fi
            if [ -f $file ]; then
                mv "$file" "._$file"
            fi

            echo "File [$file] successfully safe removed."

        else

            if [ -e "._$file" ]; then
                echo "Error: The file [$file] has already been safe removed."
            
            else
                echo "Error: The file [$file] does not exist."

            fi
        fi

        done
fi

